spring:
  rabbitmq:
    host: ip
    port: 5672
    username: windy
    password: 123456
    virtual-host: /
    #开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8090
